MODEL 'Обработка заказа';
DIAGRAM GRAPHIC A-0;
TITLE 'Обработка заказа';
BOX 1;
NAME '{}Принять заказ';
BOX COORDINATES (0.1800,0.2900) (0.3300,0.1800);
ENDBOX;
BOX 2;
NAME '{}Проверить оплату';
BOX COORDINATES (0.4700,0.5800) (0.6200,0.4700);
ENDBOX;
BOX 3;
NAME '{}Отгрузить товар';
BOX COORDINATES (0.7600,0.8700) (0.9100,0.7600);
ENDBOX;
ARROWSEG 1;
SOURCE BORDER I1;
PATH (0.0240,0.2350) (0.1800,0.2350);
LABEL '{}Заказ клиента';
SINK BOX 1I1;
ENDSEG;
ARROWSEG 2;
SOURCE BORDER C1;
PATH (0.2550,0.0320) (0.2550,0.1800);
LABEL '{}Регламент обработки';
SINK BOX 1C1;
ENDSEG;
ARROWSEG 3;
SOURCE BORDER M1;
PATH (0.2550,0.2900) (0.2550,0.9850);
LABEL '{}Менеджер';
SINK BOX 1M1;
ENDSEG;
ARROWSEG 4;
SOURCE BORDER C2;
PATH (0.5450,0.0320) (0.5450,0.4700);
LABEL '{}Договор с банком';
SINK BOX 2C1;
ENDSEG;
ARROWSEG 5;
SOURCE BORDER M2;
PATH (0.8350,0.8700) (0.8350,0.9850);
LABEL '{}Склад';
SINK BOX 3M1;
ENDSEG;
ARROWSEG 6;
SOURCE BOX 1O1;
PATH (0.3300,0.2350) (0.3400,0.2350) (0.3400,0.5250) (0.4700,0.5250);
LABEL '{}Подтверждённый заказ';
SINK BOX 2I1;
ENDSEG;
ARROWSEG 7;
SOURCE BOX 2O1;
PATH (0.6200,0.5250) (0.6400,0.5250) (0.6400,0.8150) (0.7600,0.8150);
LABEL '{}Оплаченный заказ';
SINK BOX 3I1;
ENDSEG;
ENDDIAGRAM;
