MODEL 'Оперативная деятельность менеджера по работе с клиентами';
DIAGRAM GRAPHIC A-0;
TITLE 'Оперативная деятельность менеджера по работе с клиентами';
BOX 1;
NAME '{}Оперативная деятельность менеджера по работе с клиентами';
BOX COORDINATES (0.4700,0.5800) (0.6200,0.4700);
DETAIL REFERENCE N A0;
ENDBOX;
ARROWSEG 1;
SOURCE BORDER I1;
PATH (0.0240,0.4920) (0.4700,0.4920);
LABEL 'Заявка клиента';
SINK BOX 1I1;
ENDSEG;
ARROWSEG 2;
SOURCE BORDER I2;
PATH (0.0240,0.5140) (0.4700,0.5140);
LABEL 'Прайс-лист';
LABEL COORDINATES (0.2470,0.4420);
SINK BOX 1I1;
ENDSEG;
ARROWSEG 3;
SOURCE BORDER I3;
PATH (0.0240,0.5360) (0.4700,0.5360);
LABEL 'Данные клиента';
SINK BOX 1I1;
ENDSEG;
ARROWSEG 4;
SOURCE BORDER I4;
PATH (0.0240,0.5580) (0.4700,0.5580);
LABEL 'Закрытый заказ-наряд';
LABEL COORDINATES (0.2470,0.4050);
SINK BOX 1I1;
ENDSEG;
ARROWSEG 5;
SOURCE BORDER C1;
PATH (0.5200,0.0320) (0.5200,0.4700);
LABEL 'Должностные обязанности';
SINK BOX 1C1;
ENDSEG;
ARROWSEG 6;
SOURCE BORDER C2;
PATH (0.5700,0.0320) (0.5700,0.4700);
LABEL 'Методика расчета';
LABEL COORDINATES (0.8184,0.2510);
SINK BOX 1C1;
ENDSEG;
ARROWSEG 7;
SOURCE BORDER M1;
PATH (0.5450,0.9850) (0.5450,0.5800);
LABEL 'Менеджер по работе с клиентами';
SINK BOX 1M1;
ENDSEG;
ARROWSEG 8;
SOURCE BOX 1O1;
PATH (0.6200,0.4883) (0.9850,0.4883);
LABEL 'Цена изделия';
SINK BORDER O1;
ENDSEG;
ARROWSEG 9;
SOURCE BOX 1O1;
PATH (0.6200,0.5067) (0.9850,0.5067);
LABEL 'Договор';
LABEL COORDINATES (0.8025,0.4347);
SINK BORDER O2;
ENDSEG;
ARROWSEG 10;
SOURCE BOX 1O1;
PATH (0.6200,0.5250) (0.9850,0.5250);
LABEL 'Спецификация';
SINK BORDER O3;
ENDSEG;
ARROWSEG 11;
SOURCE BOX 1O1;
PATH (0.6200,0.5433) (0.9850,0.5433);
LABEL 'Заказ-наряд';
LABEL COORDINATES (0.8025,0.3903);
SINK BORDER O4;
ENDSEG;
ARROWSEG 12;
SOURCE BOX 1O1;
PATH (0.6200,0.5617) (0.9850,0.5617);
LABEL 'Акт приемки-передачи';
SINK BORDER O5;
ENDSEG;
ENDDIAGRAM;
DIAGRAM GRAPHIC A0;
TITLE 'Оперативная деятельность менеджера по работе с клиентами';
BOX 1;
NAME '{}Обработать заявку';
BOX COORDINATES (0.1875,0.2900) (0.3025,0.1800);
ENDBOX;
BOX 2;
NAME '{}Расчет стоимости изделия';
BOX COORDINATES (0.3375,0.4350) (0.4525,0.3250);
DETAIL REFERENCE N A2;
ENDBOX;
BOX 3;
NAME '{}Оформить договор';
BOX COORDINATES (0.4875,0.5800) (0.6025,0.4700);
ENDBOX;
BOX 4;
NAME '{}Оформить спецификацию';
BOX COORDINATES (0.6375,0.7250) (0.7525,0.6150);
ENDBOX;
BOX 5;
NAME '{}Оформить акт приемки-передачи';
BOX COORDINATES (0.7875,0.8700) (0.9025,0.7600);
ENDBOX;
ARROWSEG 1;
SOURCE BORDER I1;
PATH (0.0240,0.2350) (0.1875,0.2350);
LABEL 'Заявка клиента';
SINK BOX 1I1;
ENDSEG;
ARROWSEG 2;
SOURCE BORDER C1;
PATH (0.2450,0.0320) (0.2450,0.1800);
LABEL 'Должностные обязанности';
SINK BOX 1C1;
ENDSEG;
ARROWSEG 3;
SOURCE BORDER M1;
PATH (0.2450,0.9850) (0.2450,0.2900);
LABEL 'Менеджер по работе с клиентами';
SINK BOX 1M1;
ENDSEG;
ARROWSEG 4;
SOURCE BORDER I2;
PATH (0.0240,0.3800) (0.3375,0.3800);
LABEL 'Прайс-лист';
SINK BOX 2I1;
ENDSEG;
ARROWSEG 5;
SOURCE BORDER C2;
PATH (0.3950,0.0320) (0.3950,0.3250);
LABEL 'Методика расчета';
SINK BOX 2C1;
ENDSEG;
ARROWSEG 6;
SOURCE BORDER C3;
PATH (0.4238,0.0320) (0.4238,0.3250);
LABEL 'Должностные обязанности';
LABEL COORDINATES (0.7730,0.1785);
SINK BOX 2C1;
ENDSEG;
ARROWSEG 7;
SOURCE BORDER M2;
PATH (0.3950,0.9850) (0.3950,0.4350);
LABEL 'Менеджер по работе с клиентами';
SINK BOX 2M1;
ENDSEG;
ARROWSEG 8;
SOURCE BOX 2O1;
PATH (0.4525,0.3800) (0.9850,0.3800);
LABEL 'Цена изделия';
SINK BORDER O1;
ENDSEG;
ARROWSEG 9;
SOURCE BORDER I3;
PATH (0.0240,0.5067) (0.4875,0.5067);
LABEL 'Данные клиента';
SINK BOX 3I1;
ENDSEG;
ARROWSEG 10;
SOURCE BORDER C4;
PATH (0.5258,0.0320) (0.5258,0.4700);
LABEL 'Методика расчета';
SINK BOX 3C1;
ENDSEG;
ARROWSEG 11;
SOURCE BORDER C5;
PATH (0.5642,0.0320) (0.5642,0.4700);
LABEL 'Должностные обязанности';
LABEL COORDINATES (0.9134,0.2510);
SINK BOX 3C1;
ENDSEG;
ARROWSEG 12;
SOURCE BORDER M3;
PATH (0.5450,0.9850) (0.5450,0.5800);
LABEL 'Менеджер по работе с клиентами';
SINK BOX 3M1;
ENDSEG;
ARROWSEG 13;
SOURCE BOX 3O1;
PATH (0.6025,0.5250) (0.9850,0.5250);
LABEL 'Договор';
SINK BORDER O2;
ENDSEG;
ARROWSEG 14;
SOURCE BORDER C6;
PATH (0.6950,0.0320) (0.6950,0.6150);
LABEL 'Должностные обязанности';
SINK BOX 4C1;
ENDSEG;
ARROWSEG 15;
SOURCE BORDER M4;
PATH (0.6950,0.9850) (0.6950,0.7250);
LABEL 'Менеджер по работе с клиентами';
SINK BOX 4M1;
ENDSEG;
ARROWSEG 16;
SOURCE BOX 4O1;
PATH (0.7525,0.6517) (0.9850,0.6517);
LABEL 'Спецификация';
SINK BORDER O3;
ENDSEG;
ARROWSEG 17;
SOURCE BOX 4O1;
PATH (0.7525,0.6883) (0.9850,0.6883);
LABEL 'Заказ-наряд';
SINK BORDER O4;
ENDSEG;
ARROWSEG 18;
SOURCE BORDER I4;
PATH (0.0240,0.7967) (0.7875,0.7967);
LABEL 'Закрытый заказ-наряд';
LABEL COORDINATES (0.4057,0.7517);
SINK BOX 5I1;
ENDSEG;
ARROWSEG 19;
SOURCE BORDER C7;
PATH (0.8450,0.0320) (0.8450,0.7600);
LABEL 'Должностные обязанности';
SINK BOX 5C1;
ENDSEG;
ARROWSEG 20;
SOURCE BORDER M5;
PATH (0.8450,0.9850) (0.8450,0.8700);
LABEL 'Менеджер по работе с клиентами';
SINK BOX 5M1;
ENDSEG;
ARROWSEG 21;
SOURCE BOX 5O1;
PATH (0.9025,0.8150) (0.9850,0.8150);
LABEL 'Акт приемки-передачи';
SINK BORDER O5;
ENDSEG;
ARROWSEG 22;
SOURCE BOX 1O1;
PATH (0.3025,0.2350) (0.3025,0.1420) (0.3663,0.1420) (0.3663,0.3250);
LABEL 'Обработанная заявка';
LABEL COORDINATES (1.2050,0.2335);
SINK BOX 2C1;
ENDSEG;
ARROWSEG 23;
SOURCE BOX 2O1;
PATH (0.4525,0.3800) (0.4725,0.3800) (0.4725,0.5433) (0.4875,0.5433);
LABEL 'Цена изделия';
SINK BOX 3I1;
ENDSEG;
ARROWSEG 24;
SOURCE BOX 3O1;
PATH (0.6025,0.5250) (0.6275,0.5250) (0.6275,0.6700) (0.6375,0.6700);
LABEL 'Договор';
SINK BOX 4I1;
ENDSEG;
ARROWSEG 25;
SOURCE BOX 3O1;
PATH (0.6025,0.5250) (0.6425,0.5250) (0.6425,0.8333) (0.7875,0.8333);
LABEL 'Договор';
SINK BOX 5I1;
ENDSEG;
ENDDIAGRAM;
DIAGRAM GRAPHIC A2;
TITLE 'Расчет стоимости изделия';
BOX 1;
NAME '{}Расчет площади и стоимости изделия';
BOX COORDINATES (0.1875,0.2900) (0.3025,0.1800);
ENDBOX;
BOX 2;
NAME '{}Расчет стоимости фурнитуры';
BOX COORDINATES (0.3375,0.4350) (0.4525,0.3250);
ENDBOX;
BOX 3;
NAME '{}Расчет стоимости материалов';
BOX COORDINATES (0.4875,0.5800) (0.6025,0.4700);
ENDBOX;
BOX 4;
NAME '{}Расчет стоимости работ';
BOX COORDINATES (0.6375,0.7250) (0.7525,0.6150);
ENDBOX;
BOX 5;
NAME '{}Расчет цены';
BOX COORDINATES (0.7875,0.8700) (0.9025,0.7600);
ENDBOX;
ARROWSEG 1;
SOURCE BORDER I1;
PATH (0.0240,0.2350) (0.1875,0.2350);
LABEL 'Прайс-лист';
SINK BOX 1I1;
ENDSEG;
ARROWSEG 2;
SOURCE BORDER C1;
PATH (0.2258,0.0320) (0.2258,0.1800);
LABEL 'Обработанная заявка';
SINK BOX 1C1;
ENDSEG;
ARROWSEG 3;
SOURCE BORDER C2;
PATH (0.2642,0.0320) (0.2642,0.1800);
LABEL 'Методика расчета';
LABEL COORDINATES (0.5126,0.1060);
SINK BOX 1C1;
ENDSEG;
ARROWSEG 4;
SOURCE BORDER M1;
PATH (0.2450,0.9850) (0.2450,0.2900);
LABEL 'Менеджер по работе с клиентами';
SINK BOX 1M1;
ENDSEG;
ARROWSEG 5;
SOURCE BORDER C3;
PATH (0.3950,0.0320) (0.3950,0.3250);
LABEL 'Методика расчета';
SINK BOX 2C1;
ENDSEG;
ARROWSEG 6;
SOURCE BORDER M2;
PATH (0.3950,0.9850) (0.3950,0.4350);
LABEL 'Менеджер по работе с клиентами';
SINK BOX 2M1;
ENDSEG;
ARROWSEG 7;
SOURCE BORDER C4;
PATH (0.5450,0.0320) (0.5450,0.4700);
LABEL 'Методика расчета';
SINK BOX 3C1;
ENDSEG;
ARROWSEG 8;
SOURCE BORDER M3;
PATH (0.5450,0.9850) (0.5450,0.5800);
LABEL 'Менеджер по работе с клиентами';
SINK BOX 3M1;
ENDSEG;
ARROWSEG 9;
SOURCE BORDER I2;
PATH (0.0240,0.6883) (0.6375,0.6883);
LABEL 'Коэффициент прямых затрат на работу';
SINK BOX 4I1;
ENDSEG;
ARROWSEG 10;
SOURCE BORDER C5;
PATH (0.6950,0.0320) (0.6950,0.6150);
LABEL 'Методика расчета';
SINK BOX 4C1;
ENDSEG;
ARROWSEG 11;
SOURCE BORDER M4;
PATH (0.6950,0.9850) (0.6950,0.7250);
LABEL 'Менеджер по работе с клиентами';
SINK BOX 4M1;
ENDSEG;
ARROWSEG 12;
SOURCE BORDER C6;
PATH (0.8450,0.0320) (0.8450,0.7600);
LABEL 'Методика расчета';
SINK BOX 5C1;
ENDSEG;
ARROWSEG 13;
SOURCE BORDER M5;
PATH (0.8450,0.9850) (0.8450,0.8700);
LABEL 'Менеджер по работе с клиентами';
SINK BOX 5M1;
ENDSEG;
ARROWSEG 14;
SOURCE BOX 5O1;
PATH (0.9025,0.8150) (0.9850,0.8150);
LABEL 'Цена изделия';
SINK BORDER O1;
ENDSEG;
ARROWSEG 15;
SOURCE BOX 1O1;
PATH (0.3025,0.2350) (0.3125,0.2350) (0.3125,0.3800) (0.3375,0.3800);
LABEL 'Стоимость площади изделия';
SINK BOX 2I1;
ENDSEG;
ARROWSEG 16;
SOURCE BOX 2O1;
PATH (0.4525,0.3800) (0.4725,0.3800) (0.4725,0.5250) (0.4875,0.5250);
LABEL 'Стоимость фурнитуры';
SINK BOX 3I1;
ENDSEG;
ARROWSEG 17;
SOURCE BOX 3O1;
PATH (0.6025,0.5250) (0.6275,0.5250) (0.6275,0.6517) (0.6375,0.6517);
LABEL 'Стоимость материалов';
SINK BOX 4I1;
ENDSEG;
ARROWSEG 18;
SOURCE BOX 4O1;
PATH (0.7525,0.6700) (0.7775,0.6700) (0.7775,0.8150) (0.7875,0.8150);
LABEL 'Стоимость работ';
SINK BOX 5I1;
ENDSEG;
ENDDIAGRAM;
